// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7IaTLkL29uql9kzs778hZWdBGiMPG84',
    appId: '1:864764432032:web:5c779f04937977258d43c5',
    messagingSenderId: '864764432032',
    projectId: 'image-da17f',
    authDomain: 'image-da17f.firebaseapp.com',
    databaseURL: 'https://image-da17f-default-rtdb.firebaseio.com',
    storageBucket: 'image-da17f.appspot.com',
    measurementId: 'G-7CKHQWN0MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEaCQK8JFSIIo0Md4EiTQxSRPsoczYFFQ',
    appId: '1:864764432032:android:d706489fe642c2f98d43c5',
    messagingSenderId: '864764432032',
    projectId: 'image-da17f',
    databaseURL: 'https://image-da17f-default-rtdb.firebaseio.com',
    storageBucket: 'image-da17f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGDbcucAuA2x7Rc9QUDqh3fYCEY8wJ3zE',
    appId: '1:864764432032:ios:c709aabe95bb60cd8d43c5',
    messagingSenderId: '864764432032',
    projectId: 'image-da17f',
    databaseURL: 'https://image-da17f-default-rtdb.firebaseio.com',
    storageBucket: 'image-da17f.appspot.com',
    iosBundleId: 'com.example.checkdeeplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGDbcucAuA2x7Rc9QUDqh3fYCEY8wJ3zE',
    appId: '1:864764432032:ios:307a08dbe06bf7098d43c5',
    messagingSenderId: '864764432032',
    projectId: 'image-da17f',
    databaseURL: 'https://image-da17f-default-rtdb.firebaseio.com',
    storageBucket: 'image-da17f.appspot.com',
    iosBundleId: 'com.example.checkdeeplink.RunnerTests',
  );
}
